# Generated by Django 5.0.2 on 2024-04-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_pointsawarded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointsawarded',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
