# Generated by Django 5.0.2 on 2024-05-03 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0003_alter_pointsawarded_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='spentPoints',
            field=models.IntegerField(default=0),
        ),
    ]
