# Generated by Django 5.0.2 on 2024-05-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0004_extendeduser_spentpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='cost',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='decoration',
            name='cost',
            field=models.IntegerField(default=25),
        ),
    ]
