# Generated by Django 5.0.3 on 2024-05-06 03:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
