# Generated by Django 5.0.3 on 2024-05-07 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0005_avatar_cost_decoration_cost'),
        ('app_user', '0008_notification_date_created'),
    ]

    operations = [
    ]
