# Generated by Django 5.0.2 on 2024-03-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='pathway',
            field=models.CharField(choices=[('LOANS', 'LoansPathway'), ('BUDGET', 'BudgetingPathway'), ('BANK', 'BankAccountsPathway'), ('TAX', 'TaxesPathway'), ('PENSION', 'PensionsPathway')], max_length=7),
        ),
    ]
