# Generated by Django 5.0.2 on 2024-03-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quiz', '0002_alter_quiz_name_alter_quiz_pathway'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fillinblanksentence',
            name='after',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fillinblanksentence',
            name='before',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fillinblanksentence',
            name='blank',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
