# Generated by Django 5.0.2 on 2024-03-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quiz', '0004_information_image_attempt_fillinblankreponse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/quizzes/info_sections'),
        ),
    ]
