# Generated by Django 5.0.2 on 2024-03-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quiz', '0005_alter_information_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fillinblankreponse',
            name='points_awarded',
        ),
        migrations.AddField(
            model_name='fillinblankanswer',
            name='points_awarded',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
