# Generated by Django 5.0.2 on 2024-04-21 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quiz', '0006_remove_fillinblankreponse_points_awarded_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsAwarded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='fillinblankanswer',
            name='points_awarded',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_quiz.pointsawarded'),
        ),
        migrations.AlterField(
            model_name='multiplechoiceresponse',
            name='points_awarded',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_quiz.pointsawarded'),
        ),
    ]
