# Generated by Django 5.0.2 on 2024-04-21 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quiz', '0007_pointsawarded_alter_fillinblankanswer_points_awarded_and_more'),
        ('app_user', '0002_pointsawarded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fillinblankanswer',
            name='points_awarded',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.pointsawarded'),
        ),
        migrations.AlterField(
            model_name='multiplechoiceresponse',
            name='points_awarded',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.pointsawarded'),
        ),
        migrations.DeleteModel(
            name='PointsAwarded',
        ),
    ]
